module.exports = {
  channel: "channel/info",
  channelclone: "channel/clone",
  channelunlock: "channel/unlock",
  role: "role/info",
  roleadd: "role/add",
  roleall: "role/all",
  rolebots: "role/bots",
  rolehoist: "role/hoist",
  rolehumans: "role/humans",
  roleicon: "role/icon",
  rolejoin: "role/join",
  rolementionable: "role/mentionable",
  roleremove: "role/remove",
  roleremoveall: "role/removeall",
  rolerename: "role/rename",
  roleusers: "role/users",
  roleperms: "role/permissions",
  server: "server/info",
  serverroles: "server/roles",
  serverbanner: "server/banner",
  sroles: "server/roles",
  ubanner: "user/banner",
  user: "user/info",
  userbanner: "user/banner",
  uroles: "user/roles",
  userperms: "user/permissions",
};
